"""
Tests for redesigned Automation UI config updating and compatibility.
"""
import os
import pytest
import requests

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "http://127.0.0.1:8000").rstrip("/")
SUPER_ADMIN = {"email": "admin@subhouz.com", "password": "SubhouzAdmin@2026"}


@pytest.fixture(scope="module")
def admin_session():
    s = requests.Session()
    r = s.post(f"{BASE_URL}/api/auth/login", json=SUPER_ADMIN, timeout=15)
    if r.status_code != 200:
        pytest.skip(f"Backend not reachable: {r.status_code}")
    s.headers.update({"Authorization": f"Bearer {r.json()['token']}"})
    return s


def test_list_workflows(admin_session):
    """Test listing workflows returns valid list."""
    r = admin_session.get(f"{BASE_URL}/api/automation/workflows")
    assert r.status_code == 200
    data = r.json()
    assert isinstance(data, list)
    assert len(data) > 0


def test_update_workflow_structured_config(admin_session):
    """Test updating a workflow with structured config generated by the new visual UI."""
    r_list = admin_session.get(f"{BASE_URL}/api/automation/workflows")
    workflows = r_list.json()
    wf = workflows[0]
    wf_id = wf["id"]

    new_config = {
        "folder": "Aadhaar",
        "autoRename": True,
        "prefix": "AAD",
        "delay": 5,
        "notifyManager": True
    }

    r_update = admin_session.put(
        f"{BASE_URL}/api/automation/workflows/{wf_id}",
        json={"config": new_config}
    )
    assert r_update.status_code == 200
    updated = r_update.json()
    assert updated["config"]["folder"] == "Aadhaar"
    assert updated["config"]["delay"] == 5
    assert updated["config"]["autoRename"] is True
